install.packages('progress', 'tidyverse', 'BiocManager')
install.packages('patchwork')
install.packages('rlist')
install.packages('devtools')

BiocManager::install('minfi')
BiocManager::install('limma')
BiocManager::install('missMethyl')
BiocManager::install('FlowSorted.Blood.450k')
BiocManager::install('FlowSorted.Blood.EPIC')
BiocManager::install('clusterProfiler')
BiocManager::install('pheatmap')
BiocManager::install('DMRcate')
BiocManager::install('annotatr')
BiocManager::install('wateRmelon')
BiocManager::install('reshape2')
BiocManager::install('RPMM')
BiocManager::install("ggpubr")
BiocManager::install("minfiData")

devtools::install_github("markgene/maxprobes")
