install.packages("progress", "tidyverse", "BiocManager")
install.packages("patchwork")
install.packages("rlist")
install.packages("devtools")
install.packages("Rserve")

install.packages("vscDebugger", repos = "https://manuelhentschel.r-universe.dev")

BiocManager::install("minfi")
BiocManager::install("limma")
BiocManager::install("missMethyl")
BiocManager::install("FlowSorted.Blood.450k")
BiocManager::install("FlowSorted.Blood.EPIC")
BiocManager::install("clusterProfiler")
BiocManager::install("pheatmap")
BiocManager::install("DMRcate")
BiocManager::install("annotatr")
BiocManager::install("wateRmelon")
BiocManager::install("reshape2")
BiocManager::install("RPMM")
BiocManager::install("ggpubr")
BiocManager::install("minfiData")
# BiocManager::install("chromoMap")
BiocManager::install("GenomicRanges")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")
BiocManager::install("karyoploteR")

devtools::install_github("markgene/maxprobes")
